### ISSUE TITLE
Switching tab does not update word count

### ISSUE THREAD

**Issue by JamesWP** [nesQuick/atom-wordcount#59] opened 2016-04-14 14:03 UTC
Recreate issue,

Open two markdown files with differing word counts.

Switch between them and the word count does not change.

**Comment by nesQuick** [comment] 2016-04-15 09:28
Hmm, that looks like a regression to me, but I can reproduce it. PR welcome :)

**Comment by JamesWP** [comment] 2016-04-15 09:50
I've never done any development in atom but ill out it on my ever growing hobby project list!


Sent from my mobile device

-------- Original message --------

**Comment by nesQuick** [comment] 2016-04-15 10:54
Hey @JamesWP I think this issue and the word count plugin would be a great start to get your feet wet with atom.

https://github.com/nesQuick/atom-wordcount/blob/master/lib/main.coffee#L64-L65

These are the lines where the event listener is attached to atom, I suspect they do not match the tab switching event. That is what I could give you as a starting point right of my hat.

If you encounter any issues with the plugin or how stuff works (it's really small and not that complicated), feel free to ask here. Or if you find any general atom questions the https://discuss.atom.io discussion board is great also IRC works well.

**Comment by nesQuick** [comment] 2016-10-07 10:30
this should be fixed by now

**Closed by nesQuick** 2016-10-07 10:30 UTC
