### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by mjswensen** [nesQuick/atom-wordcount#25] opened 2015-03-04 02:57 UTC
Steps to reproduce:

1. Update atom-wordcount
2. Close update pane.

The error also occurs when opening and closing the settings view, each time.

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [wordcount](https://github.com/nesQuick/atom-wordcount) package, v2.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Users/mjs/.atom/packages/wordcount/lib/wordcount-view.coffee:5

TypeError: Cannot read property 'split' of undefined
  at WordcountView.module.exports.WordcountView.attachOrDestroy (/Users/mjs/.atom/packages/wordcount/lib/wordcount-view.coffee:5:3)
  at status-bar.<anonymous> (/Users/mjs/.atom/packages/wordcount/lib/wordcount-view.coffee:1:1)
  at status-bar.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at status-bar.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:44:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:328:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app/src/pane.js:322:19)
  at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:293:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:393:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:457:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:179:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -5:18.2 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -5:17.9 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:17.4 core:move-down (atom-text-editor.editor.is-focused)
     -5:16.9 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:16.7 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -5:16.7 snippets:expand (atom-text-editor.editor.is-focused)
     -5:16.7 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -5:16.7 editor:indent (atom-text-editor.editor.is-focused)
     -5:16.2 editor:move-line-up (atom-text-editor.editor.is-focused)
     -5:14.3 core:move-up (atom-text-editor.editor.is-focused)
     -5:14.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  3x -5:13.8 core:move-left (atom-text-editor.editor.is-focused)
     -5:11.2 core:save (atom-text-editor.editor.is-focused)
  2x -5:04.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -5:03.2 core:save (atom-text-editor.editor.is-focused)
     -1:15.7 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "web-view",
      "linter-scalac",
      "minimap-git-diff",
      "minimap-color-highlight",
      "minimap"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "destroyEmptyPanes": false,
    "projectHome": "/Users/mjs/Projects"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
atom-browser-webview, v0.6.0
atom-color-highlight, v3.0.8
atom-spotify, v1.2.0
docblockr, v0.6.3
editorconfig, v0.3.0
emmet, v2.3.4
git-log, v0.3.0
language-scala, v1.1.0
language-swift, v0.3.0
linter, v0.12.0
permute, v0.1.0
project-manager, v1.15.5
project-palette-finder, v2.4.16
seti-syntax, v0.3.3
seti-ui, v0.6.3
svg-preview, v0.5.1
tasks, v1.3.0
wordcount, v2.0.0

# Dev
No dev packages
```

**Comment by mjswensen** [comment] 2015-03-04 03:03
Also happens when switching between panes.

**Comment by nesQuick** [comment] 2015-03-04 09:50
@mjswensen what do you have configured in your wordcount config?

![screen_shot_2015-03-04_at_10_48_45](https://cloud.githubusercontent.com/assets/584259/6481254/2b45157a-c25c-11e4-9057-2d52ffe85b39.png)

I can't reproduce it, that's why I'm wondering.

**Comment by AluisioASG** [comment] 2015-03-04 11:38
Just had the same issue.  Disabling doesn't help, the window has to be restarted.
Default settings.

**Comment by DavidLGoldberg** [comment] 2015-03-04 16:51
+1

**Comment by nesQuick** [comment] 2015-03-04 16:57
@DavidLGoldberg +1 for your PR fixing it ;)

**Comment by mjswensen** [comment] 2015-03-04 21:10
@nesQuick The default, as shown in your screenshot. I also noticed that it happened any time I opened a new file. I also had the symptom that @AluisioASG pointed out, where the window had to be restarted to resolve the issue after disabling the plugin.

Perhaps there is a conflict with some other plugin?

**Comment by nesQuick** [comment] 2015-03-04 23:09
this issue should be fixed now, please check if it works for you now, as I never could reproduce it.

**Closed** 2015-03-04 23:08 UTC

**Comment by AluisioASG** [comment] 2015-03-05 00:03
Seems to be working for me.

**Comment by mjswensen** [comment] 2015-03-05 00:18
@nesQuick after an initial test, it seems to be working great. Thank you!

**Comment by nesQuick** [comment] 2015-03-05 00:19
glad it works now for you :)

**Comment by DavidLGoldberg** [comment] 2015-03-05 01:56
Hey, was just trying to show love :)

Fixed for me it looks like.  Thanks!
